spring:
  application:
    name: user-service
  profiles:
    # Default profile when running locally from the IDE
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: false

---

spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 1.5
        max-attempts: 30
